env:
  contexts:
    - name: "BOLA Test Context"
      urls:
        - "http://localhost:8080"
      includePaths:
        - "http://localhost:8080/api/users/.*"
      authentication:
        method: manualAuthentication
      sessionManagement:
        method: cookie
      users:
        - name: jwtUser
          credentials:
            authHeaderValue: "Bearer {{token}}"

  vars:
    token: "<REPLACE_ME>"

jobs:
  - type: activeScan
    parameters:
      context: "BOLA Test Context"
      user: jwtUser
      policy: Default Policy

  - type: report
    parameters:
      template: traditional-html
      reportDir: zap-reports
      reportFile: zap-bola-report.html
