env:
  contexts:
    - name: "BOLA Test Context"
      urls:
        - "http://localhost:8080"
      includePaths:
        - "http://localhost:8080/api/users/.*"

  vars:
    baseUrl: "http://localhost:8080"
    authToken: "Bearer {{token}}"

jobs:
  - type: requestor
    parameters:
      context: "BOLA Test Context"
      requests:
        - url: "{{baseUrl}}/api/users/1"
          method: GET
          headers:
            - "Authorization: {{authToken}}"
        - url: "{{baseUrl}}/api/users/2"
          method: GET
          headers:
            - "Authorization: {{authToken}}"
        - url: "{{baseUrl}}/api/users/3"
          method: GET
          headers:
            - "Authorization: {{authToken}}"
        - url: "{{baseUrl}}/api/users/4"
          method: GET
          headers:
            - "Authorization: {{authToken}}"
        - url: "{{baseUrl}}/api/users/5"
          method: GET
          headers:
            - "Authorization: {{authToken}}"

  - type: activeScan
    parameters:
      context: "BOLA Test Context"
      policy: Default Policy

  - type: report
    parameters:
      template: traditional-html
      reportDir: zap/zap-reports
      reportFile: zap-bola-report.html
