env:
  contexts:
    - name: "BOLA Test Context"
      urls:
        - "http://localhost:8080"
      includePaths:
        - "http://localhost:8080/api/users/.*"
      authentication:
        method: formBasedAuthentication
        parameters:
          loginPageUrl: "http://localhost:8080/login"
          loginRequestUrl: "http://localhost:8080/api/auth/login"
          loginRequestBody: "username=client&password=client123"
      sessionManagement:
        method: cookie
      users:
        - name: clientUser
          credentials:
            username: client
            password: client123

  vars:
    baseUrl: "http://localhost:8080"

jobs:
  - type: requestor
    parameters:
      user: clientUser
      requests:
        - url: "{{baseUrl}}/api/users/1"
          method: GET
        - url: "{{baseUrl}}/api/users/2"
          method: GET
        - url: "{{baseUrl}}/api/users/3"
          method: GET
        - url: "{{baseUrl}}/api/users/4"
          method: GET
        - url: "{{baseUrl}}/api/users/5"
          method: GET
        - url: "{{baseUrl}}/api/users/6"
          method: GET
        - url: "{{baseUrl}}/api/users/7"
          method: GET
        - url: "{{baseUrl}}/api/users/8"
          method: GET
        - url: "{{baseUrl}}/api/users/9"
          method: GET
        - url: "{{baseUrl}}/api/users/10"
          method: GET

  - type: activeScan
    parameters:
      context: "BOLA Test Context"
      user: clientUser
      policy: Default Policy

  - type: report
    parameters:
      template: traditional-html
      reportDir: zap/zap-reports
      reportFile: zap-bola-report.html
